import sys
import os
import requests
import time
import json
import logging
from datetime import datetime

# Set up minimal logging
logger = logging.getLogger(__name__)

# Constants for NSE URLs
NSE_BASE_URL = "https://www.nseindia.com"
NSE_OPTIONS_CONTRACT_INFO_URL = "https://www.nseindia.com/api/option-chain-contract-info?symbol={}"
NSE_OPTIONS_V3_INDEX_URL = "https://www.nseindia.com/api/option-chain-v3?type=Indices&symbol={}&expiry={}"
NSE_OPTIONS_V3_EQUITY_URL = "https://www.nseindia.com/api/option-chain-v3?type=Equity&symbol={}&expiry={}"

# Consistent headers to mimic a real modern browser
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8",
    "Accept-Language": "en-IN,en;q=0.9,hi;q=0.8",
    "Accept-Encoding": "gzip, deflate",  # Removed 'br' to avoid decoding issues if brotli not installed
    "Connection": "keep-alive"
}

class NSEFetcher:
    def __init__(self):
        self.session = requests.Session()
        self.session.headers.update(HEADERS)
        self.cookies_dict = {}
        self.cookies_initialized = False

    def _init_cookies(self):
        """NSE API requires session cookies generated by hitting the option-chain page first."""
        try:
            self.session.cookies.clear()
            logger.info("Hitting lander: https://www.nseindia.com/option-chain")
            r = self.session.get("https://www.nseindia.com/option-chain", timeout=10)
            self.cookies_dict = dict(r.cookies)
            logger.info(f"Lander response: {r.status_code}, Cookies extracted: {len(self.cookies_dict)}")
            self.cookies_initialized = True
        except Exception as e:
            logger.error(f"Failed to initialize NSE cookies: {e}")

    def fetch_option_chain(self, symbol, is_index=False):
        """Fetches option chain data from NSE."""
        if not self.cookies_initialized:
            self._init_cookies()
        
        clean_symbol = symbol
        if symbol in ["^NSEI", "NIFTY 50", "NIFTY"]:
            clean_symbol = "NIFTY"
            is_index = True
        elif symbol in ["^NSEBANK", "BANKNIFTY"]:
            clean_symbol = "BANKNIFTY"
            is_index = True
        elif symbol.endswith(".NS"):
            clean_symbol = symbol.replace(".NS", "")
            
        # Specific headers for the API call
        referer = f"https://www.nseindia.com/option-chain?symbol={clean_symbol}" if is_index else f"https://www.nseindia.com/get-quotes/derivatives?symbol={clean_symbol}"

        api_headers = HEADERS.copy()
        api_headers.update({
            "Accept": "application/json, text/plain, */*",
            "Referer": referer,
            "Sec-Fetch-Dest": "empty",
            "Sec-Fetch-Mode": "cors",
            "Sec-Fetch-Site": "same-origin",
            "X-Requested-With": "XMLHttpRequest"
        })

        # 1. Fetch info to get expiry dates
        info_url = NSE_OPTIONS_CONTRACT_INFO_URL.format(clean_symbol)
        expiry_dates = []
        
        for attempt in range(2):
            try:
                if not self.cookies_initialized:
                    self._init_cookies()
                
                logger.info(f"Attempting to fetch contract info for {clean_symbol} to get expiries")
                response = self.session.get(info_url, headers=api_headers, cookies=self.cookies_dict, timeout=10)
                if response.status_code == 200:
                    data = response.json()
                    expiry_dates = data.get("expiryDates", [])
                    if expiry_dates:
                        break
                    else:
                        logger.warning(f"No expiry dates found in response for {clean_symbol}")
                elif response.status_code in [401, 403]:
                    logger.warning(f"Status {response.status_code} for {clean_symbol}. Resetting session.")
                    self.cookies_initialized = False
                    time.sleep(1)
            except Exception as e:
                logger.error(f"Error fetching contract info: {e}")
                self.cookies_initialized = False
                time.sleep(1)
                
        if not expiry_dates:
            logger.warning(f"Could not retrieve expiry dates for {clean_symbol}")
            return {"current": None, "next": None}

        current_expiry = expiry_dates[0]
        next_expiry = expiry_dates[1] if len(expiry_dates) > 1 else None
        
        options_data = {"current": None, "next": None}
        
        # 2. Fetch specific expiry data using V3 endpoint
        url_template = NSE_OPTIONS_V3_INDEX_URL if is_index else NSE_OPTIONS_V3_EQUITY_URL
        
        for exp_key, exp_date in [("current", current_expiry), ("next", next_expiry)]:
            if not exp_date: continue
            
            data_url = url_template.format(clean_symbol, exp_date)
            try:
                logger.info(f"Fetching V3 option data for {exp_date}")
                res = self.session.get(data_url, headers=api_headers, cookies=self.cookies_dict, timeout=10)
                if res.status_code == 200:
                    res_data = res.json()
                    records = res_data.get("records", {})
                    exp_data = records.get("data", [])
                    underlying_price = records.get("underlyingValue", 0)
                    if exp_data:
                        options_data[exp_key] = self._extract_metrics(exp_data, exp_date, underlying_price)
            except Exception as e:
                logger.error(f"Error fetching v3 data for {exp_date}: {e}")
                
        return options_data

    def _extract_metrics(self, exp_data, exp_date, underlying_price):
        """Extracts Max OI strikes, Max Pain, and ATM Straddle for a specific expiry array."""
        try:
            max_call_oi = 0; max_call_strike = 0
            max_put_oi = 0; max_put_strike = 0
            
            strikes = []
            for item in exp_data:
                strike = item.get("strikePrice", 0)
                strikes.append(strike)
                ce = item.get("CE", {})
                if ce:
                    ce_oi = ce.get("openInterest", 0)
                    if ce_oi > max_call_oi:
                        max_call_oi = ce_oi
                        max_call_strike = strike
                pe = item.get("PE", {})
                if pe:
                    pe_oi = pe.get("openInterest", 0)
                    if pe_oi > max_put_oi:
                        max_put_oi = pe_oi
                        max_put_strike = strike
            
            # ATM Straddle & Implied Move
            straddle_price = 0
            implied_move = 0
            atm_strike = 0
            
            if underlying_price > 0 and strikes:
                atm_strike = min(strikes, key=lambda x: abs(x - underlying_price))
                atm_item = next((item for item in exp_data if item.get("strikePrice") == atm_strike), None)
                if atm_item:
                    ce_ask = atm_item.get("CE", {}).get("askPrice", 0)
                    pe_ask = atm_item.get("PE", {}).get("askPrice", 0)
                    if not ce_ask: ce_ask = atm_item.get("CE", {}).get("lastPrice", 0)
                    if not pe_ask: pe_ask = atm_item.get("PE", {}).get("lastPrice", 0)
                    
                    straddle_price = float(ce_ask) + float(pe_ask)
                    
                    try:
                        # Simple Implied Move for the expiry: (Straddle / Price) * 100
                        implied_move = (straddle_price / underlying_price) * 100
                    except Exception:
                        pass

            # Simplistic Max Pain Calculation
            strikes = sorted(list(set(strikes)))
            min_pain = float('inf')
            max_pain_strike = 0
            for potential_pain_strike in strikes:
                total_pain = 0
                for item in exp_data:
                    strike = item.get("strikePrice", 0)
                    ce_oi = item.get("CE", {}).get("openInterest", 0)
                    pe_oi = item.get("PE", {}).get("openInterest", 0)
                    if potential_pain_strike > strike:
                        total_pain += (potential_pain_strike - strike) * ce_oi
                    if strike > potential_pain_strike:
                        total_pain += (strike - potential_pain_strike) * pe_oi
                if total_pain < min_pain:
                    min_pain = total_pain
                    max_pain_strike = potential_pain_strike
                    
            return {
                "expiry": exp_date,
                "underlying_price": round(underlying_price, 2),
                "max_call_oi_strike": max_call_strike if max_call_strike > 0 else None,
                "max_put_oi_strike": max_put_strike if max_put_strike > 0 else None,
                "max_pain": max_pain_strike if max_pain_strike > 0 else None,
                "straddle": round(straddle_price, 2) if straddle_price > 0 else None,
                "implied_move": round(implied_move, 4) if implied_move > 0 else None,
                "atm_strike": atm_strike
            }
        except Exception as e:
            logger.error(f"Error parsing option data metrics: {e}")
            return None

def get_nse_option_chain(symbol, is_index=False):
    fetcher = NSEFetcher()
    return fetcher.fetch_option_chain(symbol, is_index)

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    test_symbols = ["NIFTY", "RELIANCE.NS"]
    for s in test_symbols:
        print(f"\n--- Testing {s} ---")
        data = get_nse_option_chain(s)
        print(json.dumps(data, indent=2))
